export const ReferrerName = {
    "android-app://org.telegram.messenger/": "Telegram",
    "android-app://com.whatsapp/": "WhatsApp",
    "android-app://com.facebook.orca/": "Facebook Messenger",
    "android-app://com.facebook.katana/": "Facebook",
    "android-app://com.instagram.android/": "Instagram",
    "android-app://com.google.android.gm/": "Gmail",
    "android-app://com.google.android.apps.messaging/": "Android Messages",
    "android-app://com.google.android.apps.photos/": "Google Photos",
    "android-app://com.google.android.apps.docs/": "Google Drive",
    "android-app://com.google.android.apps.maps/": "Google Maps",
    "android-app://com.google.android.youtube/": "YouTube",
    "android-app://com.google.android.apps.tachyon/": "Google Duo",
    "android-app://com.google.android.apps.meetings/": "Google Meet",
    "android-app://com.google.android.apps.classroom/": "Google Classroom",
    "android-app://com.google.android.apps.docs.editors.sheets/": "Google Sheets",
    "android-app://com.google.android.apps.docs.editors.slides/": "Google Slides",
    "android-app://com.google.android.apps.docs.editors.docs/": "Google Docs",
    "ios-app://com.apple.mobilemail/": "Mail",
    "ios-app://com.apple.mobilesafari/": "Safari",
    "ios-app://com.apple.MobileSMS/": "Messages",
    "ios-app://com.apple.Maps/": "Maps",
    "ios-app://com.apple.Music/": "Music",
    "ios-app://com.apple.calculator/": "Calculator",
    "ios-app://com.apple.camera/": "Camera",
    "https://web.telegram.org/a/": "Telegram",
    "https://web.telegram.org/z/": "Telegram",
    "https://web.whatsapp.com/": "WhatsApp",
    "android-app://org.telegram.plus/": "Telegram",
}