export const ReferrerName = {
	"org.telegram.messenger/": "Telegram",
	"com.whatsapp/": "WhatsApp",
	"com.facebook.orca/": "Facebook Messenger",
	"com.facebook.katana/": "Facebook",
	"com.instagram.android/": "Instagram",
	"com.google.android.gm/": "Gmail",
	"com.google.android.apps.messaging/": "Android Messages",
	"com.google.android.apps.photos/": "Google Photos",
	"com.google.android.apps.docs/": "Google Drive",
	"com.google.android.apps.maps/": "Google Maps",
	"com.google.android.youtube/": "YouTube",
	"com.google.android.apps.tachyon/": "Google Duo",
	"com.google.android.apps.meetings/": "Google Meet",
	"com.google.android.apps.classroom/": "Google Classroom",
	"com.google.android.apps.docs.editors.sheets/": "Google Sheets",
	"com.google.android.apps.docs.editors.slides/": "Google Slides",
	"com.google.android.apps.docs.editors.docs/": "Google Docs",
	"com.apple.mobilemail/": "Mail",
	"com.apple.mobilesafari/": "Safari",
	"com.apple.MobileSMS/": "Messages",
	"com.apple.Maps/": "Maps",
	"com.apple.Music/": "Music",
	"com.apple.calculator/": "Calculator",
	"com.apple.camera/": "Camera",
	"web.telegram.org": "Telegram",
	"web.whatsapp.com": "WhatsApp",
	"org.telegram.plus/": "Telegram",
	"org.telegram": "Telegram",
	"web.telegram": "Telegram",
	t: "X [ex: Twitter]",
	"com.linkedin": "linkedin",
	"l.facebook": "facebook",
	lnkd: "linkedin",
	"l.instagram.com": "instagram",
	"l.messenger.com": "messenger",
	"m.youtube.com": "youtube",
};
