export {
  getUniqueVisitors,
  getPageViews,
  getAverageTime,
  getBounceRate,
  getPages,
  getLoc,
  getDevices,
  getReferer,
  getOS,
  getBrowser,
  getVisitorsByDate,
  getOnlineVisitors,
  getEvents,
  getUtmSources,
  getNewVisitors,
} from "./analysis"
